#pragma config(Sensor, in1,    middletop,      sensorReflection)
#pragma config(Sensor, in2,    middlebottom,   sensorReflection)
#pragma config(Sensor, dgtl1,  emergencystop,  sensorTouch)
#pragma config(Sensor, dgtl2,  firstbutton,    sensorTouch)
#pragma config(Sensor, dgtl3,  secondbutton,   sensorTouch)
#pragma config(Sensor, dgtl4,  thirdbutton,    sensorTouch)
#pragma config(Sensor, dgtl5,  top,            sensorTouch)
#pragma config(Sensor, dgtl6,  bottom,         sensorTouch)
#pragma config(Motor,  port2,           leftmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightmotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:Vex Elevator
  Team Members:Jacob Jeter, Cade Fleaher, Allison Mcgehee, Kenzie Yarbrough
  Date:12/2/14
  Section:3.1.7


  Task Description:
	Elevator

  Pseudocode:


*/

task main()
{                                     //Program begins, insert code within curly braces
	while (SensorValue[emergencystop] != 1)
  {
    int firstfloor = 0;
    int secondfloor = 0;
    int thirdfloor = 0;
    while (firstfloor == 0)
    {
    	if (SensorValue[firstbutton] == 1) firstfloor = 1;
      if (SensorValue[secondbutton] == 1) firstfloor = 2;
    	if (SensorValue[thirdbutton] == 1) firstfloor = 3;
  };
		while (secondfloor == 0)
    {
    	if (SensorValue[firstbutton] == 1) secondfloor = 1;
      if (SensorValue[secondbutton] == 1) secondfloor = 2;
    	if (SensorValue[thirdbutton] == 1) secondfloor = 3;
  };
  	while (thirdfloor == 0)
    {
    	if (SensorValue[firstbutton] == 1) thirdfloor = 1;
      if (SensorValue[secondbutton] == 1) thirdfloor = 2;
    	if (SensorValue[thirdbutton] == 1) thirdfloor = 3;
  };
if (condition)
{
  body
}
if (condition)
{
  body
}
if (condition)
{
  body
}
if (condition)
{
  body
}
if (condition)
{
  body
}
if (condition)
{
  body
}if (condition)
{
  body
}
if (condition)
{
  body
}
if (condition)
{
  body
}

	}
		startMotor(leftmotor, 127);
		startMotor(rightmotor, 127);
		waitUntil(SensorValue[bottom] == 1);
		stopMotor(leftmotor);
		stopMotor(rightmotor);

}
