#pragma config(Sensor, in1,    midfloor,      sensorReflection)
#pragma config(Sensor, dgtl1,  emergencystop,  sensorTouch)
#pragma config(Sensor, dgtl2,  firstbutton,    sensorTouch)
#pragma config(Sensor, dgtl3,  secondbutton,   sensorTouch)
#pragma config(Sensor, dgtl4,  thirdbutton,    sensorTouch)
#pragma config(Sensor, dgtl5,  top,            sensorTouch)
#pragma config(Sensor, dgtl6,  bottom,         sensorTouch)
#pragma config(Motor,  port2,           leftmotor,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:Vex Elevator
  Team Members:Jacob Jeter, Cade Fleaher, Allison Mcgehee, Kenzie Yarbrough
  Date:12/2/14
  Section:3.1.7


  Task Description:
	Elevator

  Pseudocode:
 If ebutton pressed => goto end
 		get input
 		go to floors in specified order
 		return to bottom floor
 Return to bottom floor

*/

task main()
{                                     //Program begins, insert code within curly braces
	while (SensorValue[emergencystop] != 1) //Stop loop if emergency button not pressed
  {
    int firstfloor = 0;    //erase the stored floors
    int secondfloor = 0;
    int thirdfloor = 0;
    int xyz = 1;
    while (firstfloor == 0) //get first floor input
    {
    	if (SensorValue[firstbutton] == 1) firstfloor = 1; //input = first floor
      if (SensorValue[secondbutton] == 1) firstfloor = 2; //input = second floor
    	if (SensorValue[thirdbutton] == 1) firstfloor = 3; //input = third floor
    	if (firstfloor == 1) untilRelease(firstbutton);//wait until button released
    	if (firstfloor == 2) untilRelease(secondbutton);
   		if (firstfloor == 3) untilRelease(thirdbutton);
  };
		while (secondfloor == 0) //get second floor input
    {
    	if (SensorValue[firstbutton] == 1) secondfloor = 1; //input = first floor
      if (SensorValue[secondbutton] == 1) secondfloor = 2;//input = second floor
    	if (SensorValue[thirdbutton] == 1) secondfloor = 3;//input = third floor
    	if (secondfloor == 1) untilRelease(firstbutton);//wait until button released
    	if (secondfloor == 2) untilRelease(secondbutton);
   		if (secondfloor == 3) untilRelease(thirdbutton);
  };
  	while (thirdfloor == 0) //get first floor input
    {
    	if (SensorValue[firstbutton] == 1) thirdfloor = 1;//input = first floor
      if (SensorValue[secondbutton] == 1) thirdfloor = 2;//input = second floor
    	if (SensorValue[thirdbutton] == 1) thirdfloor = 3;//input = third floor
    	if (thirdfloor == 1) untilRelease(firstbutton);//wait until button released
    	if (thirdfloor == 2) untilRelease(secondbutton);
   		if (thirdfloor == 3) untilRelease(thirdbutton);
  };
  if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
if (firstfloor == 1) //if firstfloor = 1
{
  	startMotor(leftmotor, -60); //go down until //go up until
  	while (SensorValue[bottom] != 1) //on bottom floor
    {
      if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
    }
		stopMotor(leftmotor);//stop motor
		wait(1); // wait for motion
}
if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
if (firstfloor == 2) //if firstfloor = 2
{
  	startMotor(leftmotor, 60); //go up until
while (SensorValue[midfloor] >= 1)//on middle floor
{
  if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
}
		stopMotor(leftmotor);//stop motor
		wait(1); // wait for motion
}
if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
if (firstfloor == 3)
{
  	startMotor(leftmotor, 60);//go up until
	while (SensorValue[top] != 1) //on top floor
    {
      if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
    }
		stopMotor(leftmotor);//stop motor
		wait(1); // wait for motion
}
if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
if (secondfloor == 1)
{
		startMotor(leftmotor, -60); //go down until
	while (SensorValue[bottom] != 1) //on bottom floor
    {
      if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
    }
		stopMotor(leftmotor);//stop motor
		wait(1); // wait for motion
}
if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
if (secondfloor == 2 && firstfloor == 1)
{
    startMotor(leftmotor, 60);//go up until
while (SensorValue[midfloor] >= 1)//on middle floor
{
  if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
}
		stopMotor(leftmotor);//stop motor
		wait(1); // wait for motion
}
if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
if (secondfloor == 2 && firstfloor == 3)
{
  	startMotor(leftmotor, -60); //go down until
while (SensorValue[midfloor] >= 1)//on middle floor
{
  if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
}
		stopMotor(leftmotor);//stop motor
		wait(1); // wait for motion
}
if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
if (secondfloor == 3)
{
  	startMotor(leftmotor, 60);//go up until
	while (SensorValue[top] != 1) //on top floor
    {
      if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
    }
		stopMotor(leftmotor);//stop motor
		wait(1); // wait for motion
}
if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
if (thirdfloor == 1)
{
  	startMotor(leftmotor, -60); //go down until
	while (SensorValue[bottom] != 1) //on bottom floor
    {
      if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
    }
		stopMotor(leftmotor);//stop motor
		wait(1); // wait for motion
}
if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
if (thirdfloor == 2 && secondfloor == 1)
{
    startMotor(leftmotor, 60);//go up until
while (SensorValue[midfloor] >= 1)//on middle floor
{
  if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
}
		stopMotor(leftmotor);//stop motor
		wait(1); // wait for motion
}
if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
if (thirdfloor == 2 && secondfloor == 3)
{
  	startMotor(leftmotor, -60); //go down until
while (SensorValue[midfloor] >= 1)//on middle floor
{
  if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
}
		stopMotor(leftmotor);//stop motor
		wait(1); // wait for motion
}
if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
if (thirdfloor == 3)
{
  startMotor(leftmotor, 60);//go up until
	while (SensorValue[top] != 1) //on top floor
    {
      if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
    }
		stopMotor(leftmotor);//stop motor
		wait(1); // wait for motion
}//return to bottom floor
if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop true, exit loop
		startMotor(leftmotor, -60); //go down until
			while (SensorValue[bottom] != 1) //on bottom floor
    {
      if (SensorValue[emergencystop] == xyz) goto estop; //if emergency stop = true, exit loop
    }
		stopMotor(leftmotor);//stop motor
	}// emergency return to bottom floor
	estop:
	startMotor(leftmotor, -60); //go down until
		waitUntil(SensorValue[bottom] == 1); //on bottom floor
		stopMotor(leftmotor);//stop motor

}
